### PR TITLE
[polyfill] get correct parent node for slot in shadow dom

### LINKED ISSUE #424: Polyfill: getParentNode returns incorrect result if target was added as a child through a shadow dom slot
Take a look at description here https://github.com/w3c/IntersectionObserver/issues/303#issuecomment-395948794

### PR DESCRIPTION
**Pull request by ennjin**
Closes #424

### CODE REVIEW

**Comment by ennjin** [comment]
@szager-chromium, @philipwalton, @dvoytenko someone can take a look at this?

File: polyfill/intersection-observer.js [hunk 1]
```diff
@@ -971,6 +971,10 @@ function getParentNode(node) {
   }
 
   if (parent && parent.assignedSlot) {
+    // If the parent is assigned into shadow root slot
```
Comment (dvoytenko) [inline polyfill/intersection-observer.js:974]: This sentence seems incomplete.

File: polyfill/intersection-observer.js [hunk 2]
```diff
@@ -971,6 +971,10 @@ function getParentNode(node) {
...
+    if (parent.assignedSlot.parentNode.host) {
```
Comment (dvoytenko) [inline polyfill/intersection-observer.js:975]: It might be better to move this part before the previous `if (parent.nodeType == 11 && parent.host)` and do something like:

```
if (parent && parent.assignedSlot) {
  parent = parent.assignedSlot.parentNode;
}
```

Then the `if (parent.nodeType == 11 && parent.host)` will do the right thing.

File: polyfill/intersection-observer.js [hunk 3]
```diff
@@ -965,6 +965,11 @@ function getParentNode(node) {
     return getFrameElement(node);
   }
 
+  // If the parent has element that is assigned through shadow root slot
+  if (parent && parent.assignedSlot) {
```
Comment (dvoytenko) [inline polyfill/intersection-observer.js:969]: This looks good, but it also means that the second `if (parent && parent.assignedSlot) {` at line 978 is no longer needed, right?

Comment (ennjin) [reply polyfill/intersection-observer.js:969]: Yeah, makes sense.

**Comment by ennjin** [comment]
Hm, is it ready to merge?

**Review by dvoytenko — APPROVED** [review]

**Comment by dvoytenko** [comment]
This change looks good to me. The owners of the repo still need to review and merge.

**Comment by ennjin** [comment]
@emilio it would be nice if you can check this :+1:

File: polyfill/intersection-observer.js [hunk 4]
```diff
@@ -965,16 +965,16 @@ function getParentNode(node) {
...
+    parent = parent.assignedSlot.parentNode
```
Comment (emilio) [inline polyfill/intersection-observer.js:970]: I don't think this is correct if the assigned slot has a box (via e.g. `slot { display: block }`).

File: polyfill/intersection-observer.js [hunk 5]
```diff
@@ -965,16 +965,16 @@ function getParentNode(node) {
     return getFrameElement(node);
   }
 
+  // If the parent has element that is assigned through shadow root slot
+  if (parent && parent.assignedSlot) {
```
Comment (emilio) [inline polyfill/intersection-observer.js:969]: Also probably this needs to be a `while (parent && parent.assignedSlot)` to handle nested slots.

**Review by emilio — COMMENTED** [review]
I'm curious what is the point of fixing up the polyfill if modern browsers all support the API correctly.

**Comment by ennjin** [comment]
> I'm curious what is the point of fixing up the polyfill if modern browsers all support the API correctly.

Actually there are customers using legacy browsers like chrome <= 50 and safari <= 11 :smile_cat:

File: polyfill/intersection-observer.js (hunk 4 above)
Comment (ennjin) [reply polyfill/intersection-observer.js:970]: > I don't think this is correct if the assigned slot has a box (via e.g. slot { display: block }).

Not sure if anyone style slot element

**Review by emilio — APPROVED** [review]
I mean, this is more correct than the existing code I guess. But we should really move the polyfill to a separate repo IMO.

**Comment by ennjin** [comment]
@emilio Thanks for review. But I have a question, when the following changes will be bumped to npm?
